=== serhatozdursun/gauge_api_testing/src/test/resources/schemas/petSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "https://petstore.swagger.io",
  "type": "object",
  "title": "The root schema",
  "default": {},
  "required": [
    "id",
    "category",
    "name",
    "tags",
    "status"
  ],
  "properties": {
    "id": {
      "id": "https://petstore.swagger.io#/properties/id",
      "type": "number",
      "title": "The id schema",
      "default": 0
    },
    "category": {
      "default": {},
      "id": "https://petstore.swagger.io#/properties/category",
      "required": [
        "id",
        "name"
      ],
      "title": "The category schema",
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "id": {
          "default": 0,
          "id": "https://petstore.swagger.io#/properties/category/properties/id",
          "title": "The id schema",
          "type": [
            "number",
            "null"
          ]
        },
        "name": {
          "default": "",
          "id": "https://petstore.swagger.io#/properties/category/properties/name",
          "title": "The name schema",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "name": {
      "default": "",
      "id": "https://petstore.swagger.io#/properties/name",
      "title": "The name schema",
      "type": [
        "string",
        "null"
      ]
    },
    "photoUrls": {
      "default": [],
      "id": "https://petstore.swagger.io#/properties/photoUrls",
      "title": "The photoUrls schema",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "id": "https://petstore.swagger.io#/properties/photoUrls/items",
        "anyOf": [
          {
            "default": "",
            "id": "https://petstore.swagger.io#/properties/photoUrls/items/anyOf/0",
            "title": "The first anyOf schema",
            "type": [
              "string",
              "null"
            ]
          }
        ]
      }
    },
    "tags": {
      "default": [],
      "id": "https://petstore.swagger.io#/properties/tags",
      "title": "The tags schema",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "id": "https://petstore.swagger.io#/properties/tags/items",
        "anyOf": [
          {
            "default": {},
            "id": "https://petstore.swagger.io#/properties/tags/items/anyOf/0",
            "required": [
              "id",
              "name"
            ],
            "title": "The first anyOf schema",
            "type": [
              "object",
              "null"
            ],
            "properties": {
              "id": {
                "default": 0,
                "id": "https://petstore.swagger.io#/properties/tags/items/anyOf/0/properties/id",
                "title": "The id schema",
                "type": [
                  "number",
                  "null"
                ]
              },
              "name": {
                "default": "",
                "id": "https://petstore.swagger.io#/properties/tags/items/anyOf/0/properties/name",
                "title": "The name schema",
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          }
        ]
      }
    },
    "status": {
      "default": "",
      "id": "https://petstore.swagger.io#/properties/status",
      "title": "The status schema",
      "type": [
        "string",
        "null"
      ]
    }
  }
}

=== serhatozdursun/gauge_api_testing/src/test/resources/payloads/petPost.json
{
  "id": 2020202112,
  "category": {
    "id": 0,
    "name": "Dog"
  },
  "name": "karabas",
  "photoUrls": [
    "https://www.karabas.com/karabas.jpg"
  ],
  "tags": [
    {
      "id": 2,
      "name": "kuçukuçu"
    },
    {
      "id": 3,
      "name": "kuş"
    }
  ],
  "status": "available"
}
